version: '3'
services:
  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - graphnode
    networks:
      - local
    ports:
      - 80:80
      - 443:80
    volumes:
      - '~/ensocean-react/build:/var/nginx/html'
      - '~/ensocean-react/conf:/etc/nginx/conf.d'
networks:
  local: