name: Build & Deploy
on:
  push:
    branches: 
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS App
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_PROD_HOST }} 
          key: ${{ secrets.SSH_KEY }}  
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            git config --global user.email "ramazan.dnmz@gmail.com"
            git config --global user.name "rdonmez"
            git config --global credential.helper store
            git clone https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PASSWORD }}@github.com/ensocean/ensocean-react.git 
            cd ensocean-react/ 
            git pull origin master 
            corepack enable
            yarn install
            yarn build
            echo 'Deployment successful...' 
 
