name: Build & Deploy
on:
  push:
    branches: 
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS App
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_PROD_HOST }} 
          key: ${{ secrets.SSH_KEY }}  
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            git clone https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PASSWORD }}@github.com/ensocean/ensocean-react.git 
            cd ensocean-react/
            git pull origin master
            npm install pm2@latest -g
            npm install -g serve
            npm run build
            pm2 start "npm run serve"
            echo 'Deployment successful..' 
 
